#!/command/with-contenv bash

for _ in {1..3}; do
  if ! (fdmove -c 2 1 \
      mysql --connect-timeout=1 -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" --port "${MYSQL_PORT}" -e "USE ${MYSQL_DB_NAME};" \
      > /dev/null); then
        exit 1 # mysql is not running
  fi
  sleep 1
done

exit # mysql is running
